import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Logo } from '../../components/AppHeader'
import { useAuth } from '../../context/useAuth'
export default function LoginPage() {
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [recovery,setRecovery]=useState(false);const [busy,setBusy]=useState(false);const {login,requestPasswordReset,isConfigured}=useAuth();const navigate=useNavigate();const location=useLocation()
  const submit=async e=>{e.preventDefault();setError('');setBusy(true);const r=await login(email,password);setBusy(false);if(r.error)return setError('No pudimos iniciar sesión. Revisa tus datos.');navigate(location.state?.from?.pathname||'/inicio',{replace:true})}
  const recover=async e=>{e.preventDefault();setError('');setBusy(true);const r=await requestPasswordReset(email);setBusy(false);if(r.error)return setError('No se pudo enviar el enlace. Verifica el correo.');setNotice('Te enviamos un enlace para restablecer tu contraseña. Revisa tu correo.');setRecovery(false)}
  return <main className="login-page"><section className="login-panel"><div className="login-content"><div className="login-brand"><Logo /></div><p className="eyebrow">PORTAL DE SALUD DIGITAL</p><h1>{recovery?'Recupera tu contraseña':'Tu salud, más cerca de ti'}</h1><p className="lead">{recovery?'Ingresa tu correo y te enviaremos un enlace seguro.':'Ingresa para gestionar tus citas y teleconsultas de manera simple y segura.'}</p>{(location.state?.notice||notice)&&<p className="form-success">{location.state?.notice||notice}</p>}<form onSubmit={recovery?recover:submit}><label>Correo electrónico<input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" placeholder="nombre@correo.com" /></label>{!recovery&&<label>Contraseña<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" placeholder="Ingresa tu contraseña" /></label>}{error&&<p className="form-error">{error}</p>}<button className="primary-button" disabled={!isConfigured||busy} type="submit">{busy?'Procesando…':recovery?'Enviar enlace de recuperación':'Ingresar al portal'}</button></form><button className="text-action" onClick={()=>setRecovery(!recovery)}>{recovery?'Volver al inicio de sesión':'¿Olvidaste tu contraseña?'}</button><p className="account-link">¿Aún no tienes una cuenta? <Link to="/registro">Regístrate</Link></p><div className="demo-notice"><b>Acceso de prototipo</b><span>Usa un correo de prueba. No registres información clínica ni datos de terceros.</span></div></div></section><aside className="login-aside"><div><span className="aside-icon">+</span><h2>Atención médica sin traslados innecesarios</h2><p>Reserva y confirma tu teleconsulta con toda la información a la vista.</p></div><small>Prototipo académico · EsSalud Digital</small></aside></main>
}
