import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Logo } from '../../components/AppHeader'
import { useAuth } from '../../context/useAuth'

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false); const [error, setError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false)
  const { login, isConfigured } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const submit = async e => { e.preventDefault(); setError(''); if (!email.trim() || !password) return setError('Ingresa tu correo y contraseña para continuar.'); setIsSubmitting(true); const result = await login(email, password); setIsSubmitting(false); if (result.error) return setError('No pudimos iniciar sesión. Revisa tus datos o confirma tu correo electrónico.'); navigate(location.state?.from?.pathname || '/inicio', { replace: true }) }
  return <main className="login-page"><section className="login-panel"><div className="login-content"><div className="login-brand"><Logo /></div><p className="eyebrow">PORTAL DE SALUD DIGITAL</p><h1>Tu salud, más cerca de ti</h1><p className="lead">Ingresa para gestionar tus citas y teleconsultas de manera simple y segura.</p>{location.state?.notice && <p className="form-success">{location.state.notice}</p>}<form onSubmit={submit} noValidate><label>Correo electrónico<input value={email} onChange={e => setEmail(e.target.value)} type="email" autoComplete="email" placeholder="nombre@correo.com" /></label><label>Contraseña<span className="password-field"><input value={password} onChange={e => setPassword(e.target.value)} type={visible ? 'text' : 'password'} autoComplete="current-password" placeholder="Ingresa tu contraseña" /><button type="button" onClick={() => setVisible(!visible)}>{visible ? 'Ocultar' : 'Ver'}</button></span></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={!isConfigured || isSubmitting} type="submit">{isSubmitting ? 'Ingresando…' : 'Ingresar al portal'}</button></form><button className="text-action" type="button">¿Olvidaste tu contraseña?</button><p className="account-link">¿Aún no tienes una cuenta? <Link to="/registro">Regístrate</Link></p><div className="demo-notice"><b>Acceso de prototipo</b><span>Usa un correo de prueba. No registres información clínica ni datos de terceros.</span></div></div></section><aside className="login-aside"><div><span className="aside-icon">+</span><h2>Atención médica sin traslados innecesarios</h2><p>Reserva y confirma tu teleconsulta con toda la información a la vista.</p></div><small>Prototipo académico · EsSalud Digital</small></aside></main>
}
