import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Logo } from '../../components/AppHeader'
import { useAuth } from '../../context/useAuth'

export default function RegisterPage() {
  const [form, setForm] = useState({ name: '', document: '', email: '', password: '', confirmPassword: '', terms: false }); const [error, setError] = useState('')
  const { register } = useAuth(); const navigate = useNavigate()
  const change = e => setForm({ ...form, [e.target.name]: e.target.type === 'checkbox' ? e.target.checked : e.target.value })
  const submit = e => { e.preventDefault(); if (!form.name.trim() || !form.document.trim() || !form.email.trim() || !form.password || !form.confirmPassword) return setError('Completa todos los campos requeridos.'); if (form.password !== form.confirmPassword) return setError('Las contraseñas no coinciden.'); if (!form.terms) return setError('Acepta los términos para continuar.'); register(form.name.trim(), form.email.trim()); navigate('/inicio', { replace: true }) }
  return <main className="login-page"><section className="login-panel register-panel"><div className="login-content"><div className="login-brand"><Logo /></div><p className="eyebrow">CREAR UNA CUENTA</p><h1>Regístrate en EsSalud Digital</h1><p className="lead">Crea tu acceso para gestionar teleconsultas de forma segura.</p><form onSubmit={submit} noValidate><label>Nombres y apellidos<input name="name" value={form.name} onChange={change} placeholder="Ej. María López" /></label><label>Documento de identidad<input name="document" value={form.document} onChange={change} inputMode="numeric" placeholder="Ingresa tu DNI" /></label><label>Correo electrónico<input name="email" value={form.email} onChange={change} type="email" placeholder="nombre@correo.com" /></label><label>Contraseña<input name="password" value={form.password} onChange={change} type="password" placeholder="Mínimo 8 caracteres" /></label><label>Confirmar contraseña<input name="confirmPassword" value={form.confirmPassword} onChange={change} type="password" placeholder="Repite tu contraseña" /></label><label className="terms"><input name="terms" checked={form.terms} onChange={change} type="checkbox" /><span>Acepto los términos y condiciones de uso del prototipo.</span></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" type="submit">Crear mi cuenta</button></form><p className="account-link">¿Ya tienes una cuenta? <Link to="/login">Inicia sesión</Link></p><div className="demo-notice"><b>Registro de demostración</b><span>Esta cuenta solo funciona en este navegador y no registra información clínica real.</span></div></div></section><aside className="login-aside"><div><span className="aside-icon">+</span><h2>Una reserva clara desde el primer paso</h2><p>Puedes revisar y corregir tu cita antes de confirmarla, sin empezar el proceso otra vez.</p></div><small>Prototipo académico · EsSalud Digital</small></aside></main>
}
