import { useEffect, useState } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { AppHeader, BackLink, Progress } from './components/AppHeader'
import ProtectedRoute from './components/ProtectedRoute'
import { AuthProvider } from './context/AuthContext.jsx'
import { useAuth } from './context/useAuth'
import LoginPage from './features/auth/LoginPage'
import RegisterPage from './features/auth/RegisterPage'
import { dates, doctors, formatDate, specialties, times } from './data/bookingData'
import './App.css'

const empty = { specialty: 'Medicina General', doctor: null, date: null, time: null, consent: false }
function useBooking() { const [booking, setBooking] = useState(() => JSON.parse(sessionStorage.getItem('essalud-booking') || JSON.stringify(empty))); useEffect(() => sessionStorage.setItem('essalud-booking', JSON.stringify(booking)), [booking]); return [booking, setBooking] }
function Layout({ children }) { return <div className="app-shell"><AppHeader />{children}</div> }
function Avatar({ person }) { return <span className={`avatar ${person.tone}`}>{person.initials}</span> }
function SummaryRow({ label, value, onEdit }) { return <div className="summary-row"><span><small>{label}</small><b>{value}</b></span>{onEdit && <button onClick={onEdit}>Editar</button>}</div> }

function Home() { const { user } = useAuth(); return <Layout><main className="home-page"><Progress step={1} /><h1>¡Hola, {user.name}!</h1><p className="lead">Bienvenida a tu portal de salud digital.</p><Link className="appointment-hero" to="/reserva/medico"><span className="hero-icon">▣</span><span><b>Agendar cita virtual</b><small>Recomendado para atención rápida</small><p>Reserve su consulta médica desde la comodidad de su casa. Sin colas ni traslados.</p></span><i>→</i></Link><p className="section-title">OTROS SERVICIOS</p><div className="service-list"><Link to="/mis-citas"><span>▣</span>Mis citas programadas<i>›</i></Link><button disabled><span>▤</span>Historial médico<i>›</i></button></div></main></Layout> }
function DoctorPage({ booking, setBooking }) { const navigate = useNavigate(); const [selected, setSelected] = useState(booking.doctor); const items = doctors.filter(item => item.specialty === booking.specialty); return <Layout><main className="booking-page"><BackLink>Inicio</BackLink><h1>Elija su médico</h1><Progress step={2} /><label className="select-label">Especialidad médica<select value={booking.specialty} onChange={e => { setBooking({ ...booking, specialty: e.target.value, doctor: null }); setSelected(null) }}>{specialties.map(item => <option key={item}>{item}</option>)}</select></label><p className="section-title">MÉDICOS DISPONIBLES</p><div className="doctor-options">{items.map(item => <button className={selected?.id === item.id ? 'doctor-option selected' : 'doctor-option'} key={item.id} onClick={() => setSelected(item)}><Avatar person={item} /><span><b>{item.name}</b><small>{item.specialty}</small><em>★ {item.rating} &nbsp;({item.opinions} opiniones)</em></span><strong>{item.available}</strong><i>{selected?.id === item.id ? '✓' : ''}</i></button>)}</div><div className="sticky-action"><span>♧ Seleccionado: <b>{selected ? selected.name : 'Ningún médico'}</b></span><button className="primary-button" disabled={!selected} onClick={() => { setBooking({ ...booking, doctor: selected }); navigate('/reserva/horario') }}>Continuar <b>→</b></button></div></main></Layout> }
function SchedulePage({ booking, setBooking }) { const navigate = useNavigate(); const [date, setDate] = useState(booking.date); const [time, setTime] = useState(booking.time); if (!booking.doctor) return <Navigate to="/reserva/medico" replace />; return <Layout><main className="booking-page"><BackLink to="/reserva/medico">Cambiar médico</BackLink><h1>Elija fecha y hora</h1><Progress step={3} /><div className="selected-provider"><Avatar person={booking.doctor} /><span><b>{booking.doctor.name}</b><small>{booking.doctor.specialty} — Teleconsulta</small></span></div><section className="calendar"><b>Julio 2025</b><div className="date-row">{dates.map(item => <button className={date?.id === item.id ? 'active' : ''} key={item.id} onClick={() => setDate(item)}><small>{item.weekday}</small><span>{item.day}</span></button>)}</div></section><p className="section-title">HORAS DISPONIBLES</p><div className="time-grid">{times.map(item => <button className={time === item ? 'active' : ''} key={item} onClick={() => setTime(item)}>{item}</button>)}</div><div className="sticky-action"><span>▣ Seleccionado: <b>{date && time ? `${formatDate(date)} — ${time}` : 'Elige un horario'}</b></span><button className="primary-button" disabled={!date || !time} onClick={() => { setBooking({ ...booking, date, time }); navigate('/reserva/revision') }}>Continuar <b>→</b></button></div></main></Layout> }
function ReviewPage({ booking, setBooking, setAppointment }) { const navigate = useNavigate(); if (!booking.doctor || !booking.date || !booking.time) return <Navigate to="/reserva/medico" replace />; const confirm = () => { const result = { ...booking, code: `TC-${Math.floor(10000 + Math.random() * 89999)}` }; localStorage.setItem('essalud-appointment', JSON.stringify(result)); setAppointment(result); navigate('/reserva/confirmacion') }; return <Layout><main className="booking-page review-page"><BackLink to="/reserva/horario">Cambiar horario</BackLink><h1>Revise su cita</h1><Progress step={4} /><p className="review-instruction">Por favor, confirme los datos. Verifique que todo esté correcto antes de continuar.</p><section className="summary-card"><SummaryRow label="MÉDICO" value={booking.doctor.name} onEdit={() => navigate('/reserva/medico')} /><SummaryRow label="ESPECIALIDAD" value={booking.specialty} onEdit={() => navigate('/reserva/medico')} /><SummaryRow label="FECHA Y HORA" value={`${formatDate(booking.date)} — ${booking.time}`} onEdit={() => navigate('/reserva/horario')} /><SummaryRow label="MODALIDAD" value="Teleconsulta (videollamada)" /></section><section className="consent-box"><b>Consentimiento para teleconsulta</b><ul><li>Acepto realizar la consulta de forma virtual.</li><li>Entiendo que mis datos médicos son confidenciales.</li></ul></section><label className="checkbox-label"><input type="checkbox" checked={booking.consent} onChange={e => setBooking({ ...booking, consent: e.target.checked })} /><span>Acepto las condiciones de la teleconsulta</span></label><p className="legal-note">Sus datos están protegidos según la Ley N.° 29733. <button>Leer más</button></p><button className="primary-button confirm-button" disabled={!booking.consent} onClick={confirm}>◉ Confirmar cita médica</button></main></Layout> }
function Confirmation({ appointment }) { if (!appointment) return <Navigate to="/mis-citas" replace />; return <Layout><main className="confirmation-page"><Progress step={5} /><div className="confirm-check">✓</div><h1>¡Cita confirmada!</h1><p className="lead">Su cita ha sido agendada exitosamente</p><section className="receipt"><b>◉ CONSTANCIA DE TELECONSULTA</b><SummaryRow label="MÉDICO ASIGNADO" value={`${appointment.doctor.name} (${appointment.specialty})`} /><SummaryRow label="FECHA PROGRAMADA" value={`${formatDate(appointment.date)} — ${appointment.time}`} /><SummaryRow label="CANAL DE ATENCIÓN" value="Enlace de teleconsulta en la app" /></section><p className="reminder">♧ Recibirá un recordatorio por SMS 24 horas antes de su cita.</p><button className="outline-button">▣ Agregar al calendario</button><Link className="outline-button" to="/mis-citas">Ver mis citas</Link><Link className="primary-button" to="/inicio">Volver al inicio</Link></main></Layout> }
function Appointments({ appointment }) { return <Layout><main className="booking-page"><BackLink>Inicio</BackLink><h1>Mis citas programadas</h1>{appointment ? <section className="appointment-card"><span className="status">Confirmada</span><h2>Teleconsulta médica</h2><p><b>{appointment.doctor.name}</b><br />{formatDate(appointment.date)} · {appointment.time}</p><button className="outline-button">Ver detalle</button></section> : <div className="empty-state"><span>▣</span><h2>No tienes citas programadas</h2><p>Cuando reserves una teleconsulta, aparecerá aquí.</p><Link className="primary-button" to="/reserva/medico">Agendar teleconsulta</Link></div>}</main></Layout> }
function AppRoutes() { const [booking, setBooking] = useBooking(); const [appointment, setAppointment] = useState(() => JSON.parse(localStorage.getItem('essalud-appointment') || 'null')); return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/registro" element={<RegisterPage />} /><Route path="/*" element={<ProtectedRoute><Routes><Route path="/inicio" element={<Home />} /><Route path="/reserva/medico" element={<DoctorPage booking={booking} setBooking={setBooking} />} /><Route path="/reserva/horario" element={<SchedulePage booking={booking} setBooking={setBooking} />} /><Route path="/reserva/revision" element={<ReviewPage booking={booking} setBooking={setBooking} setAppointment={setAppointment} />} /><Route path="/reserva/confirmacion" element={<Confirmation appointment={appointment} />} /><Route path="/mis-citas" element={<Appointments appointment={appointment} />} /><Route path="*" element={<Navigate to="/inicio" replace />} /></Routes></ProtectedRoute>} /></Routes> }
export default function App() { return <AuthProvider><BrowserRouter><AppRoutes /></BrowserRouter></AuthProvider> }
