import { useEffect, useState } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { AppHeader, BackLink, Progress } from './components/AppHeader'
import ProtectedRoute from './components/ProtectedRoute'
import { AuthProvider } from './context/AuthContext.jsx'
import { useAuth } from './context/useAuth'
import LoginPage from './features/auth/LoginPage'
import RegisterPage from './features/auth/RegisterPage'
import ResetPasswordPage from './features/auth/ResetPasswordPage'
import { supabase } from './lib/supabase'
import './App.css'

const emptyBooking = { specialty: 'Medicina General', doctor: null, slotId: null, date: null, time: null, consent: false }
const normalizeDoctor = row => ({ id: row.id, name: row.full_name, specialty: row.specialty, rating: row.rating, opinions: row.opinions_count, initials: row.initials, tone: row.avatar_tone })
const formatDate = value => value ? new Intl.DateTimeFormat('es-PE', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date(`${value}T12:00:00`)).replace(/^./, letter => letter.toUpperCase()) : ''
const formatTime = value => { const [hour, minute] = value.slice(0, 5).split(':').map(Number); return `${hour % 12 || 12}:${String(minute).padStart(2, '0')} ${hour >= 12 ? 'PM' : 'AM'}` }
const dateShort = value => new Intl.DateTimeFormat('es-PE', { weekday: 'short', day: 'numeric' }).format(new Date(`${value}T12:00:00`))
const downloadCalendar = appointment => { const stamp = `${appointment.date.replaceAll('-', '')}T${appointment.time.replaceAll(':', '').slice(0, 4)}00`; const content = `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:${appointment.id || appointment.code}@essalud-digital\r\nDTSTAMP:${stamp}\r\nDTSTART:${stamp}\r\nSUMMARY:Teleconsulta - ${appointment.doctor.name}\r\nDESCRIPTION:Teleconsulta médica por videollamada\r\nEND:VEVENT\r\nEND:VCALENDAR`; const url = URL.createObjectURL(new Blob([content], { type: 'text/calendar;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'teleconsulta.ics'; link.click(); URL.revokeObjectURL(url) }
function useBooking() { return useState(emptyBooking) }
function Layout({ children }) { const [helpOpen,setHelpOpen]=useState(false); return <div className="app-shell"><AppHeader onHelp={()=>setHelpOpen(true)} />{children}{helpOpen&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="help-title"><section className="help-modal"><button className="modal-close" type="button" aria-label="Cerrar ayuda" onClick={()=>setHelpOpen(false)}>×</button><h2 id="help-title">¿Necesitas ayuda?</h2><p>Para reservar una teleconsulta, elige un profesional, selecciona fecha y hora, revisa los datos y confirma tu cita.</p><p>Si necesitas cambiar una elección, usa “Editar” antes de confirmar.</p><button className="primary-button" type="button" onClick={()=>setHelpOpen(false)}>Entendido</button></section></div>}</div> }
function Avatar({ person }) { return <span className={`avatar ${person.tone}`}>{person.initials}</span> }
function SummaryRow({ label, value, onEdit }) { return <div className="summary-row"><span><small>{label}</small><b>{value}</b></span>{onEdit && <button onClick={onEdit}>Editar</button>}</div> }
function Loading({ message = 'Cargando información…' }) { return <p className="data-message">{message}</p> }
function DataError({ message }) { return <p className="data-error">No pudimos cargar los datos. {message}</p> }

function Home() { const { user } = useAuth(); const displayName = user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'Usuario'; return <Layout><main className="home-page"><Progress step={1} /><h1>¡Hola, {displayName}!</h1><p className="lead">Bienvenida a tu portal de salud digital.</p><Link className="appointment-hero" to="/reserva/medico"><span className="hero-icon">▣</span><span><b>Agendar cita virtual</b><small>Recomendado para atención rápida</small><p>Reserve su consulta médica desde la comodidad de su casa. Sin colas ni traslados.</p></span><i>→</i></Link><p className="section-title">OTROS SERVICIOS</p><div className="service-list"><Link to="/mis-citas"><span>▣</span>Mis citas programadas<i>›</i></Link><button disabled><span>▤</span>Historial médico<i>›</i></button></div></main></Layout> }

function DoctorPage({ booking, setBooking }) {
  const navigate = useNavigate(); const [selected, setSelected] = useState(booking.doctor); const [items, setItems] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { let active = true; supabase.from('doctors').select('*').eq('is_active', true).order('full_name').then(({ data, error: requestError }) => { if (!active) return; setLoading(false); if (requestError) setError(requestError.message); else setItems(data.map(normalizeDoctor)) }); return () => { active = false } }, [])
  const specialties = [...new Set(items.map(item => item.specialty))]; const filtered = items.filter(item => item.specialty === booking.specialty)
  return <Layout><main className="booking-page"><BackLink>Inicio</BackLink><h1>Elija su médico</h1><Progress step={2} />{loading ? <Loading /> : error ? <DataError message={error} /> : <><label className="select-label">Especialidad médica<select value={booking.specialty} onChange={e => { setBooking({ ...booking, specialty: e.target.value, doctor: null, slotId: null, date: null, time: null }); setSelected(null) }}>{specialties.map(item => <option key={item}>{item}</option>)}</select></label><p className="section-title">MÉDICOS DISPONIBLES</p><div className="doctor-options">{filtered.map(item => <button className={selected?.id === item.id ? 'doctor-option selected' : 'doctor-option'} key={item.id} onClick={() => setSelected(item)}><Avatar person={item} /><span><b>{item.name}</b><small>{item.specialty}</small><em>★ {item.rating} &nbsp;({item.opinions} opiniones)</em></span><strong>Disponible</strong><i>{selected?.id === item.id ? '✓' : ''}</i></button>)}</div><div className="sticky-action"><span>♧ Seleccionado: <b>{selected ? selected.name : 'Ningún médico'}</b></span><button className="primary-button" disabled={!selected} onClick={() => { setBooking({ ...booking, doctor: selected, slotId: null, date: null, time: null }); navigate('/reserva/horario') }}>Continuar <b>→</b></button></div></>}</main></Layout>
}

function SchedulePage({ booking, setBooking }) {
  const navigate = useNavigate(); const [slots, setSlots] = useState([]); const [date, setDate] = useState(booking.date); const [time, setTime] = useState(booking.time); const [slotId, setSlotId] = useState(booking.slotId); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { if (!booking.doctor) return undefined; let active = true; supabase.from('availability_slots').select('*').eq('doctor_id', booking.doctor.id).eq('is_available', true).order('appointment_date').order('appointment_time').then(({ data, error: requestError }) => { if (!active) return; setLoading(false); if (requestError) setError(requestError.message); else setSlots(data) }); return () => { active = false } }, [booking.doctor])
  if (!booking.doctor) return <Navigate to="/reserva/medico" replace />
  const availableDates = [...new Set(slots.map(item => item.appointment_date))]; const visibleSlots = slots.filter(item => item.appointment_date === date); const monthLabel = date ? new Intl.DateTimeFormat('es-PE', { month: 'long', year: 'numeric' }).format(new Date(`${date}T12:00:00`)).replace(/^./, letter => letter.toUpperCase()) : 'Fechas disponibles'
  const chooseDate = value => { setDate(value); setTime(null); setSlotId(null) }; const chooseSlot = item => { setTime(item.appointment_time); setSlotId(item.id) }
  return <Layout><main className="booking-page"><BackLink to="/reserva/medico">Cambiar médico</BackLink><h1>Elija fecha y hora</h1><Progress step={3} /><div className="selected-provider"><Avatar person={booking.doctor} /><span><b>{booking.doctor.name}</b><small>{booking.doctor.specialty} — Teleconsulta</small></span></div>{loading ? <Loading /> : error ? <DataError message={error} /> : availableDates.length === 0 ? <DataError message="No hay horarios disponibles para este médico." /> : <><section className="calendar"><b>{monthLabel}</b><p className="calendar-help">Elige una de las fechas con atención disponible.</p><div className="date-row">{availableDates.map(item => <button className={date === item ? 'active' : ''} key={item} onClick={() => chooseDate(item)}><small>{dateShort(item).split(' ')[0]}</small><span>{new Date(`${item}T12:00:00`).getDate()}</span></button>)}</div></section><p className="section-title">HORAS DISPONIBLES</p><div className="time-grid">{visibleSlots.map(item => <button className={slotId === item.id ? 'active' : ''} key={item.id} onClick={() => chooseSlot(item)}>{formatTime(item.appointment_time)}</button>)}</div><div className="sticky-action"><span>▣ Seleccionado: <b>{date && time ? `${formatDate(date)} — ${formatTime(time)}` : 'Elige un horario'}</b></span><button className="primary-button" disabled={!slotId} onClick={() => { setBooking({ ...booking, slotId, date, time }); navigate('/reserva/revision') }}>Continuar <b>→</b></button></div></>}</main></Layout>
}

function ReviewPage({ booking, setBooking, setAppointment }) {
  const navigate = useNavigate(); const [error, setError] = useState(''); const [isSubmitting, setIsSubmitting] = useState(false)
  if (!booking.doctor || !booking.slotId || !booking.date || !booking.time) return <Navigate to="/reserva/medico" replace />
  const confirm = async () => { setError(''); setIsSubmitting(true); const { data, error: requestError } = await supabase.rpc('book_appointment', { p_slot_id: booking.slotId }); setIsSubmitting(false); if (requestError) return setError(requestError.message.includes('no longer available') ? 'Este horario acaba de ser reservado. Elige otro para continuar.' : 'No se pudo registrar la cita. Inténtalo nuevamente.'); setAppointment({ ...booking, code: data.confirmation_code, id: data.id }); setBooking(emptyBooking); navigate('/reserva/confirmacion') }
  return <Layout><main className="booking-page review-page"><BackLink to="/reserva/horario">Cambiar horario</BackLink><h1>Revise su cita</h1><Progress step={4} /><p className="review-instruction">Por favor, confirme los datos. Verifique que todo esté correcto antes de continuar.</p><section className="summary-card"><SummaryRow label="MÉDICO" value={booking.doctor.name} onEdit={() => navigate('/reserva/medico')} /><SummaryRow label="ESPECIALIDAD" value={booking.specialty} onEdit={() => navigate('/reserva/medico')} /><SummaryRow label="FECHA Y HORA" value={`${formatDate(booking.date)} — ${formatTime(booking.time)}`} onEdit={() => navigate('/reserva/horario')} /><SummaryRow label="MODALIDAD" value="Teleconsulta (videollamada)" /></section><section className="consent-box"><b>Consentimiento para teleconsulta</b><ul><li>Acepto realizar la consulta de forma virtual.</li><li>Entiendo que mis datos médicos son confidenciales.</li></ul></section><label className="checkbox-label"><input type="checkbox" checked={booking.consent} onChange={e => setBooking({ ...booking, consent: e.target.checked })} /><span>Acepto las condiciones de la teleconsulta</span></label>{error && <p className="form-error booking-error">{error}</p>}<p className="legal-note">Sus datos están protegidos según la Ley N.° 29733. <button>Leer más</button></p><button className="primary-button confirm-button" disabled={!booking.consent || isSubmitting} onClick={confirm}>{isSubmitting ? 'Confirmando…' : '◉ Confirmar cita médica'}</button></main></Layout>
}

function Confirmation({ appointment }) { if (!appointment) return <Navigate to="/mis-citas" replace />; return <Layout><main className="confirmation-page"><Progress step={5} /><div className="confirm-check">✓</div><h1>¡Cita confirmada!</h1><p className="lead">Su cita ha sido agendada exitosamente</p><section className="receipt"><b>◉ CONSTANCIA DE TELECONSULTA</b><SummaryRow label="MÉDICO ASIGNADO" value={`${appointment.doctor.name} (${appointment.specialty})`} /><SummaryRow label="FECHA PROGRAMADA" value={`${formatDate(appointment.date)} — ${formatTime(appointment.time)}`} /><SummaryRow label="CANAL DE ATENCIÓN" value="Enlace de teleconsulta en la app" /></section><p className="reminder">♧ Recibirá un recordatorio por SMS 24 horas antes de su cita.</p><button className="outline-button" onClick={()=>downloadCalendar(appointment)}>▣ Agregar al calendario</button><Link className="outline-button" to="/mis-citas">Ver mis citas</Link><Link className="primary-button" to="/inicio">Volver al inicio</Link></main></Layout> }

function Appointments() {
  const [items, setItems] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [expandedId, setExpandedId] = useState(null)
  useEffect(() => { let active = true; supabase.from('appointments').select('id,status,confirmation_code,created_at,availability_slots(appointment_date,appointment_time,doctors(full_name,specialty))').order('created_at', { ascending: false }).then(({ data, error: requestError }) => { if (!active) return; setLoading(false); if (requestError) setError(requestError.message); else setItems(data) }); return () => { active = false } }, [])
  return <Layout><main className="booking-page"><BackLink>Inicio</BackLink><h1>Mis citas programadas</h1>{loading ? <Loading /> : error ? <DataError message={error} /> : items.length ? items.map(item => { const slot = item.availability_slots; const doctor = slot?.doctors; const isExpanded = expandedId === item.id; return <section className="appointment-card" key={item.id}><span className="status">Confirmada</span><h2>Teleconsulta médica</h2><p><b>{doctor?.full_name}</b><br />{formatDate(slot?.appointment_date)} · {formatTime(slot?.appointment_time || '00:00')}</p>{isExpanded && <div className="appointment-extra"><span>Especialidad</span><b>{doctor?.specialty}</b><span>Código de cita</span><b>{item.confirmation_code}</b><span>Modalidad</span><b>Videollamada</b></div>}<button className="outline-button" onClick={() => setExpandedId(isExpanded ? null : item.id)}>{isExpanded ? 'Ocultar detalle' : 'Ver detalle'}</button></section> }) : <div className="empty-state"><span>▣</span><h2>No tienes citas programadas</h2><p>Cuando reserves una teleconsulta, aparecerá aquí.</p><Link className="primary-button" to="/reserva/medico">Agendar teleconsulta</Link></div>}</main></Layout>
}

function AppRoutes() { const [booking, setBooking] = useBooking(); const [appointment, setAppointment] = useState(null); return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/registro" element={<RegisterPage />} /><Route path="/restablecer-contrasena" element={<ResetPasswordPage />} /><Route path="/*" element={<ProtectedRoute><Routes><Route path="/inicio" element={<Home />} /><Route path="/reserva/medico" element={<DoctorPage booking={booking} setBooking={setBooking} />} /><Route path="/reserva/horario" element={<SchedulePage booking={booking} setBooking={setBooking} />} /><Route path="/reserva/revision" element={<ReviewPage booking={booking} setBooking={setBooking} setAppointment={setAppointment} />} /><Route path="/reserva/confirmacion" element={<Confirmation appointment={appointment} />} /><Route path="/mis-citas" element={<Appointments />} /><Route path="*" element={<Navigate to="/inicio" replace />} /></Routes></ProtectedRoute>} /></Routes> }
export default function App() { return <AuthProvider><BrowserRouter><AppRoutes /></BrowserRouter></AuthProvider> }
